/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.RayOfHope.PersonCare;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organizations.Organization;
import Business.Organizations.PersonCareOrganization;
import Business.Person.Person;
import Business.Person.PersonDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EducationAssistWorkRequest;
import Business.WorkQueue.MedicalAssistanceWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author khyati
 */
public class ViewCompletePersonDetails extends javax.swing.JPanel {

    /**
     * Creates new form ViewCompletePersonDetails
     */
    
    JPanel userProcessContainer;
    Person person;
    UserAccount account;
    PersonCareOrganization personCareOrganization;
    Enterprise enterprise;
    EcoSystem business;
    PersonDirectory personDirectory;
    Network network;
    
    public ViewCompletePersonDetails(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business, PersonDirectory personDirectory, Person person,boolean flag) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.person = person;
        this.account = account;
        this.personCareOrganization = (PersonCareOrganization) organization;
        this.enterprise = enterprise;
        this.business = business;
        this.personDirectory = personDirectory;
        
        for (Network net : business.getNetworkCatalog()) {
            for (Enterprise ent : net.getEnterpriseDirectory().getEnterpriseList()) {
                if (ent.equals(enterprise)) {
                    network = net;
                }
            }
        }
        disableInput();
        
        nameTextField.setText(person.getName());
        if (person.getGender().equalsIgnoreCase("Male")) {
            maleRDB.setSelected(true);
        } else if (person.getGender().equalsIgnoreCase("female")) {
            femaleRDB.setSelected(true);
        }
        jXDatePicker1.setDate(person.getRegistrationDate());
        txtMark.setText(person.getIdentificationMark());
        bpText.setText(String.valueOf(person.getBP()));
        pulseText.setText(String.valueOf(person.getPulseRate()));
        tempText.setText(String.valueOf(person.getBodytemp()));
        respRateText.setText(String.valueOf(person.getRespirationRate()));
        medicalTextArea.setText(person.getMedicalStatus());
        txtDOB.setText(String.valueOf(person.getPersonAge()));
        
        displayImage();
        
        populaterequestTable();
        
        btnRequestFunds.setEnabled(!person.isFinancialHelp() && flag);
        requestMedicalHelpBtn.setEnabled(!person.isMedicalHelp());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nameTextField = new javax.swing.JTextField();
        lblDOB = new javax.swing.JLabel();
        maleRDB = new javax.swing.JRadioButton();
        femaleRDB = new javax.swing.JRadioButton();
        lblGender = new javax.swing.JLabel();
        lblHeading = new javax.swing.JLabel();
        lblPic = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblPersonalInfo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblMedicalInfo = new javax.swing.JLabel();
        tempText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        respRateText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        medicalTextArea = new javax.swing.JTextArea();
        lblRegistDate = new javax.swing.JLabel();
        lblIdenMark = new javax.swing.JLabel();
        btnRequestFunds = new javax.swing.JButton();
        requestMedicalHelpBtn = new javax.swing.JButton();
        lblBP = new javax.swing.JLabel();
        bpText = new javax.swing.JTextField();
        lblPulse = new javax.swing.JLabel();
        pulseText = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblRequest = new javax.swing.JTable();
        txtDOB = new javax.swing.JTextField();
        txtMark = new javax.swing.JTextField();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();

        jPanel1.setBackground(new java.awt.Color(246, 226, 187));
        jPanel1.setMinimumSize(new java.awt.Dimension(50, 50));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 190, 30));

        lblDOB.setText("Age");
        jPanel1.add(lblDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 100, 30));

        maleRDB.setText("Male");
        maleRDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRDBActionPerformed(evt);
            }
        });
        jPanel1.add(maleRDB, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, -1, -1));

        femaleRDB.setText("Female");
        jPanel1.add(femaleRDB, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 100, 100, 60));

        lblGender.setText("Gender");
        jPanel1.add(lblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 130, 30));

        lblHeading.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblHeading.setForeground(new java.awt.Color(71, 52, 58));
        lblHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeading.setText("View Person Details");
        jPanel1.add(lblHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 223, 40));
        jPanel1.add(lblPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 70, 170, 180));

        lblName.setText("Name");
        jPanel1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 110, 30));

        lblPersonalInfo.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblPersonalInfo.setText("Personal Info");
        jPanel1.add(lblPersonalInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 121, 20));

        jLabel7.setText("Temperature");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, 27));

        lblMedicalInfo.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblMedicalInfo.setText("Medical Info");
        jPanel1.add(lblMedicalInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 143, -1));

        tempText.setMinimumSize(new java.awt.Dimension(50, 50));
        jPanel1.add(tempText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 190, 30));

        jLabel9.setText("Respiration Rate");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, 27));

        respRateText.setMinimumSize(new java.awt.Dimension(50, 50));
        jPanel1.add(respRateText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 190, -1));

        jLabel10.setText("Medical History:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, -1, 25));

        medicalTextArea.setColumns(20);
        medicalTextArea.setRows(5);
        jScrollPane1.setViewportView(medicalTextArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 370, 90));

        lblRegistDate.setText("Registration Date");
        jPanel1.add(lblRegistDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 130, 30));

        lblIdenMark.setText("Identification mark");
        jPanel1.add(lblIdenMark, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 130, 30));

        btnRequestFunds.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnRequestFunds.setText("Request Funds");
        btnRequestFunds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestFundsActionPerformed(evt);
            }
        });
        jPanel1.add(btnRequestFunds, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 480, 180, 30));

        requestMedicalHelpBtn.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        requestMedicalHelpBtn.setText("Request Medical Help");
        requestMedicalHelpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestMedicalHelpBtnActionPerformed(evt);
            }
        });
        jPanel1.add(requestMedicalHelpBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 430, 180, 30));

        lblBP.setText("Blood Pressure");
        jPanel1.add(lblBP, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 100, 30));

        bpText.setMinimumSize(new java.awt.Dimension(50, 50));
        jPanel1.add(bpText, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 310, 190, -1));

        lblPulse.setText("Pulse Rate");
        jPanel1.add(lblPulse, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, -1, 27));

        pulseText.setMinimumSize(new java.awt.Dimension(50, 50));
        jPanel1.add(pulseText, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 370, 190, -1));

        tblRequest.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tblRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Person Id", "Sender", "Receiver", "Result", "Remarks"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblRequest);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 550, 800, 104));
        jPanel1.add(txtDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 190, 30));
        jPanel1.add(txtMark, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 160, 190, 30));
        jPanel1.add(jXDatePicker1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 190, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1243, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 824, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 824, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void maleRDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRDBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleRDBActionPerformed

    private void btnRequestFundsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestFundsActionPerformed
        String data = "";
        RequestFinancialHelp panel = new RequestFinancialHelp(userProcessContainer, account, personCareOrganization, enterprise, business, personDirectory, person, data);
        this.userProcessContainer.add("RequestFinanceHelp", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRequestFundsActionPerformed

    private void requestMedicalHelpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestMedicalHelpBtnActionPerformed
        RequestMedicalHelp panel = new RequestMedicalHelp(userProcessContainer, account, personCareOrganization, enterprise, business, personDirectory, person);
        this.userProcessContainer.add("RequestMedicalHelp", panel);
        CardLayout layout = (CardLayout) this.userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_requestMedicalHelpBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bpText;
    private javax.swing.JButton btnRequestFunds;
    private javax.swing.JRadioButton femaleRDB;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private javax.swing.JLabel lblBP;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblIdenMark;
    private javax.swing.JLabel lblMedicalInfo;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPersonalInfo;
    private javax.swing.JLabel lblPic;
    private javax.swing.JLabel lblPulse;
    private javax.swing.JLabel lblRegistDate;
    private javax.swing.JRadioButton maleRDB;
    private javax.swing.JTextArea medicalTextArea;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField pulseText;
    private javax.swing.JButton requestMedicalHelpBtn;
    private javax.swing.JTextField respRateText;
    private javax.swing.JTable tblRequest;
    private javax.swing.JTextField tempText;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtMark;
    // End of variables declaration//GEN-END:variables
    
    public void displayImage() {
        BufferedImage image = null; 
        String filename = person.getImageDetails(); 
        try {
            image = ImageIO.read(new File(filename));  
        } catch (Exception e) { 
            JOptionPane.showMessageDialog(null, "File not found");
        }
        ImageIcon icon = new ImageIcon(image);
        lblPic.setIcon(icon);
    }
    
    public void disableInput() {
        txtDOB.setEnabled(false);
        femaleRDB.setEnabled(false);
        bpText.setEnabled(false);
        txtMark.setEnabled(false);
        jXDatePicker1.setEnabled(false);
        maleRDB.setEnabled(false);
        medicalTextArea.setEnabled(false);
        nameTextField.setEnabled(false);
        pulseText.setEnabled(false);
        respRateText.setEnabled(false);
        tempText.setEnabled(false);
    }
    
    public void populaterequestTable() {
        DefaultTableModel dtms = (DefaultTableModel) tblRequest.getModel();
        dtms.setRowCount(0);
        for (WorkRequest request : account.getWorkQueue().getWorkRequestList()) {
            if (request.getPersonId() == person.getPersonId()) {

                Object[] row = new Object[dtms.getColumnCount()];
                row[0] = request;
                row[1] = request.getPersonId();
                row[2] = request.getSender();
                row[3] = request.getReceiver();
                if (request instanceof MedicalAssistanceWorkRequest) {
                    String result = ((MedicalAssistanceWorkRequest) request).getTestResult();
                    String remarks = ((MedicalAssistanceWorkRequest) request).getRemark();
                    row[5] = remarks;
                    row[4] = result == null ? "Waiting" : result;
                }
                if (request instanceof EducationAssistWorkRequest) {
                    row[4] = request.getStatus();
                    row[5] = ((EducationAssistWorkRequest) request).getRemarks();
                }
                dtms.addRow(row);
            }
        }
    }
}
