/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.Pharmacy;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organizations.Organization;
import Business.Organizations.PersonCareOrganization;
import Business.Organizations.PharmacistOrganization;
import Business.Person.Person;
import Business.Person.PersonDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PersonCareWorkRequest;
import Business.WorkQueue.PharmacistAssistWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author parag
 */
public class PharmacyProcessJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PharmacyProcessJPanel
     */
    
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private EcoSystem business;
    PharmacistAssistWorkRequest request;
    private PersonDirectory personDirectory;
    private Person person;
    Network network;
    
    public PharmacyProcessJPanel(JPanel userProcessContainer, PharmacistAssistWorkRequest request, UserAccount userAccount, Enterprise enterprise, Person person, PersonDirectory personDirectory, EcoSystem business, PharmacistOrganization pharmacyOrganization) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.person = person;
        this.personDirectory = personDirectory;
        this.business = business;
        
        for (Network n : business.getNetworkCatalog()) {
            for (Enterprise ent : n.getEnterpriseDirectory().getEnterpriseList()) {
                if (ent.equals(enterprise)) {
                    network = n;
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblComments = new javax.swing.JLabel();
        txtComments = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(246, 226, 187));

        jPanel1.setBackground(new java.awt.Color(246, 226, 187));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(71, 52, 58));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pharmacist Feedback");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 378, -1));

        lblComments.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblComments.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComments.setText("Comments");
        jPanel1.add(lblComments, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 100, 20));
        jPanel1.add(txtComments, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 310, 130));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 100, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Screen Shot 2021-12-12 at 3.23.00 PM.png"))); // NOI18N
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 590, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if (txtComments.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter message");
        } else {
            request.setResult(txtComments.getText());
            request.setStatus("Delivered");
            PersonCareWorkRequest temp = new PersonCareWorkRequest();
            temp.setStatus("Medically Fit");
            temp.setMessage("Person has been medicated");
            temp.setSender(userAccount);
            temp.setResult("Completed");
            temp.setPersonId(request.getPersonId());
            temp.setPersonName(request.getPersonName());
            if (this.personDirectory != null && this.personDirectory.getPersonList().size() > 0) {
                for (Person p: this.personDirectory.getPersonList()) {
                    if (request.getPersonId() == p.getPersonId()) {
                        if ("Acquired".equalsIgnoreCase(p.getStatus())) {
                            p.setMedicalHelp(false);
                            temp.setIsAcquiredReq(false);
                        } else {
                            temp.setIsAcquiredReq(true);
                        }
                        break;
                    }
                }
            }
            Organization org = null;
            for (Network network : business.getNetworkCatalog()) {
                for (Enterprise ent : network.getEnterpriseDirectory().getEnterpriseList()) {
                    for (Organization organization : ent.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof PersonCareOrganization) {
                            org = organization;
                            break;
                        }
                    }
                }
            }
            if (org != null) {
                org.getWorkQueue().getWorkRequestList().add(temp);
                userAccount.getWorkQueue().getWorkRequestList().add(temp);
                business.getWorkQueue().getWorkRequestList().add(temp);
            }
        }
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        PharmacyJPanel panel = (PharmacyJPanel) component;
        panel.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblComments;
    private javax.swing.JTextField txtComments;
    // End of variables declaration//GEN-END:variables
}
