/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Sponsor;

import Business.Adopter.AdopterDirectory;
import Business.Donor.Donor;
import Business.Donor.DonorDirectory;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organizations.DonorOrganization;
import Business.Organizations.Organization;
import Business.Person.PersonDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DonorWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shwetabulchandani
 */
public class StatusSponsor extends javax.swing.JPanel {

    /**
     * Creates new form StatusSponsor
     */
    JPanel userProcessContainer;
    UserAccount account;
    Enterprise enterprise;
    EcoSystem business;
    DonorOrganization donororganization;
    Donor donor;
    PersonDirectory persondirectory;
    DonorDirectory donorDirectory;
    
    public StatusSponsor(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business, AdopterDirectory adopterdirectory, PersonDirectory persondirectory, DonorDirectory donorDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.enterprise = enterprise;
        this.business = business;
        this.donororganization = (DonorOrganization) organization;
        this.persondirectory = persondirectory;
        this.donorDirectory = donorDirectory;
        for (Donor a : donorDirectory.getDonorList()) {
            if (a.getDonorName().equals(account.getUsername())) {
                donor = a;
            }
        }
        populateWorkRequestTable();
    }
    
    public void populateWorkRequestTable(){
        DefaultTableModel table = (DefaultTableModel) workReqTable.getModel();
        table.setRowCount(0);
        for (WorkRequest req : business.getWorkQueue().getWorkRequestList()) {
            if (req instanceof DonorWorkRequest) {
                DonorWorkRequest request = (DonorWorkRequest) req;
                req.setReceiver(account);
                if (request.getUserName().equalsIgnoreCase(account.getUsername())) {
                    Object[] row = new Object[table.getColumnCount()];
                    row[0] = req;
                    row[1] = req.getReceiver();
                    row[2] = req.getPersonId();
                    row[3] = req.getPersonName();
                    row[4] = ((DonorWorkRequest) req).getAmount();
                    row[5] = req.getStatus();
                    table.addRow(row);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        workReqTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(246, 226, 187));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(71, 52, 58));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Payment Status");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 380, 30));

        workReqTable.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        workReqTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Reciever", "Person ID", "Person Name", "Amount", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(workReqTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 910, 137));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/paymentstatus.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 860, 520));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable workReqTable;
    // End of variables declaration//GEN-END:variables
}
